apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssrv-kubeapi-deployment
  namespace: l4proxy
  labels:
    app: ssrv-kubeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssrv-kubeapi
  template:
    metadata:
      labels:
        app: ssrv-kubeapi
    spec:
      containers:
      - name: ssrv-kubeapi
        image: samsonbabu/haproxy:0.2
        ports:
        - containerPort: 443
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/etc/haproxy
      volumes:
      - name: config-volume
        configMap:
          name: ssrv-kubeapi-config
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
---
apiVersion: v1
kind: Service
metadata:
  name: ssrv-kubeapi
  namespace: l4proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 67.172.159.163/32
  - 1.2.3.4/32
  selector:
    app: ssrv-kubeapi
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
